[package]
authors = ["panicbit <panicbit.dev@gmail.com>"]
build = "build.rs"
name = "leap"
version = "0.1.0"

[build-dependencies]
cmake = "0.1"

[dependencies]
libc = "0.2"

[dev-dependencies]
rustbox = "0.11"
